ocr_models:
  - name: nanonets/Nanonets-OCR2-3B
    prompt: Extract the text from the above document as if you were reading it naturally.
    batch_size: 10
    max_workers: 3
    num_samples: 100
    active: true
    save_results: true
    results_dir: results
    extra: null
  - name: rednote-hilab/dots.ocr
    prompt: Extract the text from the above document as if you were reading it naturally.
    batch_size: 10
    max_workers: 3
    num_samples: 100
    active: false
    save_results: true
    results_dir: results
    extra: null